# Generated by Django 4.1.1 on 2022-12-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Categoría')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('categorias', models.ManyToManyField(to='main.categoria')),
            ],
            options={
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.PositiveBigIntegerField()),
                ('accion', models.CharField(choices=[('pl', 'play'), ('pu', 'purchase')], max_length=10)),
                ('horasJugadas', models.FloatField(verbose_name='Horas Jugadas')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.juego')),
            ],
            options={
                'ordering': ('idUsuario', 'horasJugadas'),
            },
        ),
    ]
