# Generated by Django 4.1.1 on 2022-12-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.TextField(unique=True, verbose_name='Título'),
        ),
    ]
