# Generated by Django 4.1.1 on 2022-12-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_juego_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='appId',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
