# Generated by Django 4.1.4 on 2022-12-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_juego_desarrollador_juego_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.URLField(null=True, verbose_name='Imagen del juego'),
        ),
    ]
